// Downloads woff2 files from Google Fonts and emits a self-hosted @font-face stylesheet.
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = process.argv[2];
const FONT_DIR = join(ROOT, "assets", "fonts");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36";

const REQUESTS = [
  {
    id: "geist",
    url: "https://fonts.googleapis.com/css2?family=Geist:wght@100..900&display=swap",
    keepSubsets: ["latin", "latin-ext"],
  },
  {
    id: "plexar",
    url: "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&display=swap",
    keepSubsets: ["arabic"],
  },
];

// Google returns blocks in a fixed subset order per family; comments name each block.
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([^*]+?)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const subset = m[1].trim();
    const body = m[2];
    const url = /url\((https:[^)]+\.woff2)\)/.exec(body)?.[1];
    const weight = /font-weight:\s*([^;]+);/.exec(body)?.[1].trim();
    const style = /font-style:\s*([^;]+);/.exec(body)?.[1].trim() ?? "normal";
    const range = /unicode-range:\s*([^;]+);/.exec(body)?.[1].trim();
    if (url) faces.push({ subset, url, weight, style, range });
  }
  return faces;
}

await mkdir(FONT_DIR, { recursive: true });
const out = [];

for (const req of REQUESTS) {
  const res = await fetch(req.url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${req.id}: ${res.status}`);
  const faces = parseFaces(await res.text()).filter((f) =>
    req.keepSubsets.includes(f.subset),
  );
  if (!faces.length) throw new Error(`${req.id}: no matching subsets`);

  for (const f of faces) {
    const safeWeight = f.weight.replace(/\s+/g, "-");
    const name = `${req.id}-${f.subset}-${safeWeight}.woff2`;
    const bin = await fetch(f.url, { headers: { "User-Agent": UA } });
    const buf = Buffer.from(await bin.arrayBuffer());
    await writeFile(join(FONT_DIR, name), buf);
    out.push({ ...f, name, family: req.id, bytes: buf.length });
    console.log(`${name}  ${(buf.length / 1024).toFixed(1)}KB`);
  }
}

const FAMILY_NAME = { geist: "Geist", plexar: "IBM Plex Sans Arabic" };
const css =
  `/* Self-hosted subsets. Generated by scripts/fetch-fonts.mjs. */\n\n` +
  out
    .map(
      (f) => `@font-face {
  font-family: "${FAMILY_NAME[f.family]}";
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url("../fonts/${f.name}") format("woff2");
  unicode-range: ${f.range};
}`,
    )
    .join("\n\n") + "\n";

await mkdir(join(ROOT, "assets", "css"), { recursive: true });
await writeFile(join(ROOT, "assets", "css", "fonts.css"), css, "utf8");
console.log(`\n${out.length} files, ${(out.reduce((a, f) => a + f.bytes, 0) / 1024).toFixed(1)}KB total`);
